#!/bin/bash
# This file is generated by hh, see https://github.com/moold/hh for details.
#> hujiang
echo "test training..."
../target/release/cycsim train -r nanopore read.bam ref.fa.gz -o read.bam.cy  # 2025-08-19 13:50:14
#> hujiang
echo "test simulation..."
../target/release/cycsim sim read.bam.cy ref.fa.gz -o sim.bam  # 2025-08-19 13:51:01
